/**
 * dsh-chat-plus — 工具闸门样式（命名空间 dsh-gate，幂等注入）。
 *
 * 两个部分：
 *  1. `/` 菜单里给两条指令补的 SVG 图标（官方宿主命令没有图标通道，见下）；
 *  2. 输入栏工具行左端的开关卡片。
 *
 * 视觉基线沿用本插件既有卡片：品牌色用 --dsw-alias-state-business-primary 家族、
 * 表面用 label-primary 的低比例 mix、圆角与描边跟 download / 供应商面板一致。
 *
 * 动效全部纯 CSS：
 *  - 卡片入场（位移淡入）；
 *  - 滑块位移 + 轨道底色过渡（.22s cubic-bezier）；
 *  - 开启瞬间一道斜向扫光（sheen，一次性 keyframe）；
 *  - 图标 hover 微放大、开启染品牌色；
 *  - 提交中脉冲呼吸；失败抖动。
 * 末尾统一用 prefers-reduced-motion 关掉全部动画与过渡（无障碍兜底）。
 *
 * 注意：本字符串用数组 join 而非模板字面量 —— 构建期的注入式 CSS 守卫
 * （build.mjs 的 assertInjectedCssStrings）会求值「赋值给标识符的模板字面量」，
 * 而 CSS 注释里的反引号会让模板提前闭合、整张样式表静默变成 false。
 */

const CSS = [
  '/* 图标资源：两条指令的 mask 图（内联 SVG，data URI）。放在 :root 上，',
  '   菜单行与胶囊共用同一份定义。stroke 用黑色，靠 mask 取形状、靠',
  '   background-color 上色，因此自动跟随主题与 hover/active 态。 */',
  ':root {',
  '  --dsh-gate-icon-computer: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 16 16\' fill=\'none\' stroke=\'%23000\' stroke-width=\'1.2\' stroke-linecap=\'round\' stroke-linejoin=\'round\'%3E%3Crect x=\'1.75\' y=\'2.75\' width=\'12.5\' height=\'8.5\' rx=\'1.5\'/%3E%3Cpath d=\'M5.75 14.25h4.5\'/%3E%3Cpath d=\'M8 11.25v3\'/%3E%3Cpath d=\'M9.6 5.4l4.2 3.2-1.9.5-.9 1.8z\' fill=\'%23000\' stroke=\'none\'/%3E%3C/svg%3E");',
  '  --dsh-gate-icon-browser: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 16 16\' fill=\'none\' stroke=\'%23000\' stroke-width=\'1.2\' stroke-linecap=\'round\' stroke-linejoin=\'round\'%3E%3Ccircle cx=\'8\' cy=\'8\' r=\'6.25\'/%3E%3Cpath d=\'M1.75 8h12.5\'/%3E%3Cpath d=\'M8 1.75c1.7 1.8 2.6 3.9 2.6 6.25S9.7 12.45 8 14.25C6.3 12.45 5.4 10.35 5.4 8S6.3 3.55 8 1.75z\'/%3E%3C/svg%3E");',
  '}',
  '',
  '/* ===== 按需工具开关卡片（输入栏工具行左端，与记忆开关同一排）========= */',
  '/*',
  ' * 一张卡片装两个开关项，而不是两枚各自成形的胶囊：',
  ' *  - 两枚独立胶囊在工具行里看起来像两个互不相干的控件，也不说明它们是一类；',
  ' *  - 卡片只有一圈描边、不铺底色（左侧记忆开关 .dsh-memory-toggle 同样是',
  ' *    background:transparent），整排读起来是「若干个输入区能力开关」，而不是',
  ' *    散落的按钮；底色会在这排浅色工具行上糊出一块灰斑，实测观感很差。',
  ' *  - 描边与项间分隔线也一并去掉（用户实机反馈「按钮周围的线条」碍眼）：控件',
  ' *    边界改由 hover/active 的底色与圆角体现，静态时与工具行融为一体。',
  ' *',
  ' * 放在 input.left 而不是 input.right：右侧紧邻模型选择器，实测文字会与之重叠。',
  ' *',
  ' * 尺寸对齐同排的记忆开关（.dsh-memory-toggle：28px 高、6px 圆角）。',
  ' *',
  ' * 两条实测定下来的硬约束（数字来自实机 DOM 探测，不是猜的）：',
  ' *  1. **必须 flex: none**。槽位容器是 display:contents（不生成盒子），真正决定',
  ' *     宽度的是官方工具行 div.uV2eYG_tools（实测 234px / 4 个子项 / gap 12px）。',
  ' *     卡片若写 flex:0 1 auto + min-width:0 会被压成 2px —— 页面上只剩一条竖线。',
  ' *     同排的记忆开关之所以没事，是因为它 min-width:auto + 内部 flex:0 0 auto，',
  ' *     自动最小尺寸=内容，压不动。这里照抄这个思路：不可压缩。',
  ' *  2. **不能在这个卡片上挂 container-type**。容器查询的宽度基准是容器自身内容',
  ' *     宽度，而卡片宽度又由内容决定 —— 一旦被挤窄就触发「隐藏文字」规则，文字没',
  ' *     了更窄，自噬到只剩图标。响应式改用 width:max-content 让内容自己定宽。',
  ' *',
  ' * 空间账：工具行 234px − 3×gap 12px − 两枚记忆开关 56px = 142px 可用。',
  ' * 两个带中文标签的开关项要约 200px，放不下；所以本卡片只留「图标 + 滑块」',
  ' * （与记忆开关的纯图标风格一致），名称与体积走 title 悬浮说明。',
  ' */',
  '.dsh-gate-card {',
  '  --dsh-gate-accent: var(--dsw-alias-state-business-primary, #4176e6);',
  '  display: inline-flex;',
  '  align-items: stretch;',
  '  flex: none;',
  '  width: max-content;',
  '  height: 28px;',
  '  box-sizing: border-box;',
  '  overflow: hidden;',
  '  border: 0;',
  '  border-radius: 6px;',
  '  background: transparent;',
  '  animation: dsh-gate-card-in .28s cubic-bezier(.2,.8,.25,1) both;',
  '  transition: background-color .22s ease, box-shadow .22s ease;',
  '}',
  '.dsh-gate-card:hover {',
  '  background: color-mix(in srgb, var(--dsh-gate-accent) 6%, transparent);',
  '  box-shadow: 0 1px 6px color-mix(in srgb, var(--dsh-gate-accent) 10%, rgba(15,17,21,.05));',
  '}',
  '@keyframes dsh-gate-card-in { from { opacity: 0; transform: translateY(2px); } to { opacity: 1; transform: none; } }',
  '',
  '/* 一项开关：图标 + 滑块（+ 开启时的计数），整项可点。 */',
  '.dsh-gate-item {',
  '  position: relative;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 4px;',
  '  flex: none;',
  '  padding: 0 6px;',
  '  border: 0;',
  '  border-radius: 6px;',
  '  background: transparent;',
  '  color: var(--dsw-alias-label-secondary, #666);',
  '  font: inherit;',
  '  font-size: 11px;',
  '  line-height: 1;',
  '  cursor: pointer;',
  '  white-space: nowrap;',
  '  transition: background-color .2s ease, color .2s ease;',
  '}',
  '/* 项间分隔线：去掉。加圆角 hover 底色后，两条竖线会让工具行看起来像表格。 */',
  '.dsh-gate-item:hover {',
  '  background: color-mix(in srgb, var(--dsh-gate-accent) 8%, transparent);',
  '  color: var(--dsw-alias-label-primary, #111);',
  '}',
  '.dsh-gate-item:active { background: color-mix(in srgb, var(--dsh-gate-accent) 14%, transparent); }',
  '.dsh-gate-item:focus-visible {',
  '  outline: 2px solid color-mix(in srgb, var(--dsh-gate-accent) 55%, transparent);',
  '  outline-offset: -2px;',
  '}',
  '.dsh-gate-item.is-on { color: var(--dsw-alias-label-primary, #111); }',
  '',
  '/* 名称：视觉隐藏但保留在无障碍树里（读屏能念出「电脑操作」），',
  '   因为工具行只有 142px 可用、放不下中文标签；鼠标说明走 title 悬浮。 */',
  '.dsh-gate-item__label {',
  '  position: absolute;',
  '  width: 1px;',
  '  height: 1px;',
  '  margin: -1px;',
  '  padding: 0;',
  '  overflow: hidden;',
  '  clip-path: inset(50%);',
  '  white-space: nowrap;',
  '  border: 0;',
  '}',
  '',
  '/* 图标：mask 取形状 + background-color 上色，自动跟随主题与状态。 */',
  '.dsh-gate-item__icon {',
  '  display: inline-block;',
  '  flex: none;',
  '  width: 13px;',
  '  height: 13px;',
  '  background-color: var(--dsw-alias-menu-icon, currentColor);',
  '  -webkit-mask-repeat: no-repeat;',
  '  mask-repeat: no-repeat;',
  '  -webkit-mask-position: center;',
  '  mask-position: center;',
  '  -webkit-mask-size: 13px 13px;',
  '  mask-size: 13px 13px;',
  '  transition: background-color .2s ease, transform .24s cubic-bezier(.2,.8,.25,1);',
  '}',
  '.dsh-gate-item[data-gate-key="computer-use"] .dsh-gate-item__icon {',
  '  -webkit-mask-image: var(--dsh-gate-icon-computer);',
  '  mask-image: var(--dsh-gate-icon-computer);',
  '}',
  '.dsh-gate-item[data-gate-key="browser-use"] .dsh-gate-item__icon {',
  '  -webkit-mask-image: var(--dsh-gate-icon-browser);',
  '  mask-image: var(--dsh-gate-icon-browser);',
  '}',
  '/* 开启：图标染品牌色；hover 时轻微放大（有反馈但不跳）。 */',
  '.dsh-gate-item.is-on .dsh-gate-item__icon { background-color: var(--dsh-gate-accent); }',
  '.dsh-gate-item:hover .dsh-gate-item__icon { transform: scale(1.12); }',
  '',
  '/* 轨道 + 滑块：关闭时滑块在左且灰，开启时右移并染品牌色。 */',
  '.dsh-gate-item__track {',
  '  position: relative;',
  '  display: inline-block;',
  '  flex: none;',
  '  width: 20px;',
  '  height: 12px;',
  '  overflow: hidden;',
  '  border-radius: 999px;',
  '  background: color-mix(in srgb, var(--dsw-alias-label-primary, #111) 16%, transparent);',
  '  transition: background-color .22s ease;',
  '}',
  '.dsh-gate-item__knob {',
  '  position: absolute;',
  '  top: 2px;',
  '  left: 2px;',
  '  width: 8px;',
  '  height: 8px;',
  '  border-radius: 999px;',
  '  background: var(--dsw-alias-bg-layer, #fff);',
  '  box-shadow: 0 1px 2px rgba(15,17,21,.28);',
  '  transition: transform .22s cubic-bezier(.2,.8,.25,1), background-color .22s ease;',
  '}',
  '.dsh-gate-item.is-on .dsh-gate-item__track {',
  '  background: linear-gradient(90deg, var(--dsh-gate-accent), color-mix(in srgb, var(--dsh-gate-accent) 62%, #7aa7ff));',
  '}',
  '.dsh-gate-item.is-on .dsh-gate-item__knob { transform: translateX(8px); }',
  '',
  '/* 开启瞬间的斜向扫光：只在点亮那一下跑一次（盖住整项）。 */',
  '.dsh-gate-item__sheen {',
  '  position: absolute;',
  '  inset: 0;',
  '  pointer-events: none;',
  '  opacity: 0;',
  '  background: linear-gradient(105deg, transparent 30%, rgba(255,255,255,.5) 50%, transparent 70%);',
  '}',
  '.dsh-gate-item.is-on .dsh-gate-item__sheen { animation: dsh-gate-sheen .62s ease-out .04s 1; }',
  '@keyframes dsh-gate-sheen {',
  '  0% { opacity: 0; transform: translateX(-120%); }',
  '  35% { opacity: .9; }',
  '  100% { opacity: 0; transform: translateX(120%); }',
  '}',
  '',
  '/* 提交中：轨道呼吸；失败：整项抖一下（不静默失败）。 */',
  '.dsh-gate-item.is-pending { cursor: progress; }',
  '.dsh-gate-item.is-pending .dsh-gate-item__track { animation: dsh-gate-pulse 1s ease-in-out infinite; }',
  '@keyframes dsh-gate-pulse { 0%, 100% { opacity: 1; } 50% { opacity: .55; } }',
  '.dsh-gate-item.is-failed {',
  '  color: var(--dsw-alias-state-error-primary, #e5484d);',
  '  animation: dsh-gate-shake .4s cubic-bezier(.36,.07,.19,.97) 1;',
  '}',
  '.dsh-gate-item.is-failed .dsh-gate-item__track { background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #e5484d) 45%, transparent); }',
  '@keyframes dsh-gate-shake {',
  '  10%, 90% { transform: translateX(-1px); }',
  '  20%, 80% { transform: translateX(2px); }',
  '  30%, 50%, 70% { transform: translateX(-3px); }',
  '  40%, 60% { transform: translateX(3px); }',
  '}',
  '',
  '/* 计数徽标：开启时显示该组会注入多少工具（上标，不占横向空间）。 */',
  '.dsh-gate-item__count {',
  '  flex: none;',
  '  margin-left: 1px;',
  '  padding: 0 3px;',
  '  border-radius: 999px;',
  '  background: color-mix(in srgb, var(--dsh-gate-accent) 18%, transparent);',
  '  color: color-mix(in srgb, var(--dsh-gate-accent) 78%, var(--dsw-alias-label-primary, #111));',
  '  font-size: 9px;',
  '  font-variant-numeric: tabular-nums;',
  '  line-height: 13px;',
  '  animation: dsh-gate-badge-in .24s cubic-bezier(.2,.8,.25,1) both;',
  '}',
  '@keyframes dsh-gate-badge-in { from { opacity: 0; transform: scale(.7); } to { opacity: 1; transform: none; } }',
  '',
  '/* 无障碍兜底：用户要求减弱动效时，全部动画与过渡关闭。 */',
  '@media (prefers-reduced-motion: reduce) {',
  '  .dsh-gate-card, .dsh-gate-item, .dsh-gate-item__icon, .dsh-gate-item__track, .dsh-gate-item__knob, .dsh-gate-item__count { transition: none; }',
  '  .dsh-gate-card, .dsh-gate-item, .dsh-gate-item__sheen, .dsh-gate-item__track, .dsh-gate-item__count { animation: none !important; }',
  '}',
  '',
  '/* ===== `/` 菜单里给两条指令补的 SVG 图标 ============================== */',
  '/*',
  ' * 为什么是 DOM 补图标而不是注册 contribution：官方 ui-commands 的',
  ' * candidates() 只对 6 个内置 definitionId 调 builtinRowFace 取图标，第三方',
  ' * 宿主命令拿不到 icon 字段；而客户端 contribution 与宿主命令同名会抛',
  ' * 「collides with a host command」，把整个 `/` 菜单炸掉。',
  ' *',
  ' * 所以这里由 MutationObserver 在菜单行上打一个 data 属性，图标本体交给纯',
  ' * CSS 的 mask（内联 SVG data URI）。::before 直接成为 flex 行的第一个 item，',
  ' * 与官方 itemIcon 同位同尺寸 —— 不插节点、不碰官方 React 树。',
  ' */',
  'button[data-dsh-gate-icon]::before {',
  '  content: "";',
  '  display: inline-block;',
  '  flex: none;',
  '  width: 14px;',
  '  height: 14px;',
  '  background-color: var(--dsw-alias-menu-icon, currentColor);',
  '  -webkit-mask-repeat: no-repeat;',
  '  mask-repeat: no-repeat;',
  '  -webkit-mask-position: center;',
  '  mask-position: center;',
  '  -webkit-mask-size: 14px 14px;',
  '  mask-size: 14px 14px;',
  '  transition: background-color .2s ease, transform .24s cubic-bezier(.2,.8,.25,1);',
  '  animation: dsh-gate-icon-in .3s cubic-bezier(.2,.8,.25,1) both;',
  '}',
  '/* 电脑操作：显示器 + 光标。 */',
  'button[data-dsh-gate-icon="computer-use"]::before {',
  '  -webkit-mask-image: var(--dsh-gate-icon-computer);',
  '  mask-image: var(--dsh-gate-icon-computer);',
  '}',
  '/* 浏览器操作：地球 + 经纬。 */',
  'button[data-dsh-gate-icon="browser-use"]::before {',
  '  -webkit-mask-image: var(--dsh-gate-icon-browser);',
  '  mask-image: var(--dsh-gate-icon-browser);',
  '}',
  '/* 高亮行：图标跟随文字变主色并轻微放大（与官方 active 态一致的手感）。 */',
  'button[data-dsh-gate-icon][aria-selected="true"]::before {',
  '  background-color: var(--dsw-alias-label-primary, currentColor);',
  '  transform: scale(1.08);',
  '}',
  '/* 悬停行：图标染品牌色。 */',
  'button[data-dsh-gate-icon]:hover::before {',
  '  background-color: var(--dsw-alias-state-business-primary, #4176e6);',
  '}',
  '@keyframes dsh-gate-icon-in {',
  '  from { opacity: 0; transform: scale(.6) rotate(-12deg); }',
  '  to { opacity: 1; transform: none; }',
  '}',
  '',
  '@media (prefers-reduced-motion: reduce) {',
  '  button[data-dsh-gate-icon]::before { transition: none; animation: none !important; }',
  '}',
].join('\n')

export const GATE_STYLES = CSS

/** 幂等注入（与其它模块同一约定）。 */
export function injectStyles(): void {
  if (typeof document === 'undefined') return
  if (document.getElementById('dsh-tools-gate-style') !== null) return
  const style = document.createElement('style')
  style.id = 'dsh-tools-gate-style'
  style.textContent = CSS
  document.head.appendChild(style)
}
