/**
 * html 卡片样式（命名空间 dtt-he，幂等注入）。
 *
 * 与 diagram / proto 卡片同一套视觉语言：去底色、细描边、柔和投影、入场浮起。
 * 唯一特别的是高度容器 —— 高度由 iframe 上报后写在行内 style 上，这里的
 * transition 负责把「内容变高」变成一次平滑生长，而不是硬跳。
 */

const CSS = [
  '/* 容器：与 dtt-diagram / dtt-proto 同一张图纸卡规格 */',
  '.dtt-he {',
  '  margin: 12px 0 4px;',
  '  border: 1px solid var(--dsw-alias-border-l3, rgba(127,127,127,.16));',
  '  border-radius: 12px;',
  '  overflow: hidden;',
  '  background: transparent;',
  '  box-shadow: 0 8px 30px rgba(20,40,90,.07);',
  '  animation: dtt-he-rise .45s cubic-bezier(.2,.8,.25,1) both;',
  '}',
  'body[data-ds-dark-theme] .dtt-he { border-color: rgba(255,255,255,.10); box-shadow: 0 10px 30px rgba(0,0,0,.55); }',
  '@keyframes dtt-he-rise {',
  '  from { opacity: 0; transform: translateY(10px) }',
  '  to { opacity: 1; transform: none }',
  '}',
  '/* 标题栏：左标题 + 字节数，右动作簇 */',
  '.dtt-he__bar {',
  '  display: flex; align-items: center; gap: 8px;',
  '  padding: 7px 8px 7px 12px;',
  '  border-bottom: 1px solid var(--dsw-alias-border-l2, rgba(127,127,127,.14));',
  '}',
  '.dtt-he__title {',
  '  font-size: 12px; font-weight: 600; opacity: .8;',
  '  white-space: nowrap; overflow: hidden; text-overflow: ellipsis; min-width: 0; flex: 1;',
  '}',
  '.dtt-he__meta { font-size: 10.5px; opacity: .38; font-variant-numeric: tabular-nums; white-space: nowrap; }',
  '.dtt-he__actions { display: flex; align-items: center; gap: 2px; flex: none; }',
  '/* 动作按钮：hover 上浮 + 底色浮现，active 用品牌色标出当前态 */',
  '.dtt-he__btn {',
  '  display: inline-flex; align-items: center; justify-content: center;',
  '  width: 24px; height: 24px; padding: 0;',
  '  border: 0; border-radius: 7px; background: transparent; color: inherit;',
  '  opacity: .5; cursor: pointer; font-family: inherit;',
  '  transition: opacity .18s ease, background-color .18s ease, transform .18s ease;',
  '}',
  '.dtt-he__btn:hover { opacity: 1; background: var(--dsw-alias-bg-layer-2, rgba(127,127,127,.12)); transform: translateY(-1px); }',
  '.dtt-he__btn:active { transform: translateY(0) scale(.94); }',
  '.dtt-he__btn:focus-visible { outline: 2px solid var(--dsw-alias-state-business-primary, #4176e6); outline-offset: 1px; }',
  '.dtt-he__btn--active { opacity: 1; color: var(--dsw-alias-state-business-primary, #4176e6); }',
  '/* 预览舞台：高度由 iframe 上报，transition 把增长做成平滑生长 */',
  '.dtt-he__stage { width: 100%; overflow: hidden; }',
  '.dtt-he__stage--settled { transition: height .28s cubic-bezier(.2,.8,.25,1); }',
  '.dtt-he__frame { display: block; width: 100%; height: 100%; border: 0; background: transparent; }',
  '/* ── 预渲染占位（流式期，围栏未闭合）────────────────────────────',
  '   结构与真卡片共用同一套骨架，闭合后只是内容换掉，尺寸与位置不跳。 */',
  '.dtt-he--pending { animation: dtt-he-rise .45s cubic-bezier(.2,.8,.25,1) both; }',
  '.dtt-he__title--muted { opacity: .5; font-weight: 500; }',
  '.dtt-he__stage--pending {',
  '  display: flex; flex-direction: column; align-items: center; justify-content: center;',
  '  gap: 12px; min-height: 116px; padding: 22px 16px; position: relative;',
  '}',
  '.dtt-he__pending { display: flex; align-items: center; gap: 9px; }',
  '/* 呼吸点：等待态唯一的常驻动效，克制到不抢成品卡片的戏 */',
  '.dtt-he__pending-dot {',
  '  width: 7px; height: 7px; border-radius: 50%; flex: none;',
  '  background: var(--dsw-alias-state-business-primary, #4176e6);',
  '  animation: dtt-he-breathe 1.4s ease-in-out infinite;',
  '}',
  '@keyframes dtt-he-breathe {',
  '  0%, 100% { opacity: .3; transform: scale(.82) }',
  '  50% { opacity: 1; transform: scale(1) }',
  '}',
  '.dtt-he__pending-text { font-size: 12px; opacity: .55; letter-spacing: .02em; }',
  '.dtt-he__pending-bytes { font-size: 10.5px; opacity: .32; font-variant-numeric: tabular-nums; }',
  '/* 不确定进度条：从左往右扫，暗示「还在长」但不确定还剩多少 */',
  '.dtt-he__pending-track {',
  '  width: min(220px, 62%); height: 3px; border-radius: 999px; overflow: hidden;',
  '  background: var(--dsw-alias-bg-layer-2, rgba(127,127,127,.14));',
  '}',
  '.dtt-he__pending-bar {',
  '  display: block; width: 38%; height: 100%; border-radius: 999px;',
  '  background: linear-gradient(90deg, transparent, var(--dsw-alias-state-business-primary, #4176e6), transparent);',
  '  animation: dtt-he-sweep 1.5s cubic-bezier(.4,0,.2,1) infinite;',
  '}',
  '@keyframes dtt-he-sweep {',
  '  0% { transform: translateX(-110%) }',
  '  100% { transform: translateX(300%) }',
  '}',
  '/* 源码视图：等宽、可横向滚动、限高 */',
  '.dtt-he__code {',
  '  margin: 0; padding: 12px 14px; max-height: 460px; overflow: auto;',
  '  font-family: var(--dsw-font-mono, ui-monospace, SFMono-Regular, Menlo, monospace);',
  '  font-size: 12px; line-height: 1.6; white-space: pre; tab-size: 2;',
  '  animation: dtt-he-fade .24s ease both;',
  '}',
  '@keyframes dtt-he-fade { from { opacity: 0 } to { opacity: 1 } }',
  '/* 全屏层：body 级 portal，玻璃质感 + 缩放入场 */',
  '.dtt-he__overlay {',
  '  position: fixed; inset: 0; z-index: 2147483000;',
  '  display: flex; flex-direction: column;',
  '  background: var(--dsw-alias-bg-layer-1, #fff);',
  '  animation: dtt-he-zoom .26s cubic-bezier(.2,.8,.25,1) both;',
  '}',
  'body[data-ds-dark-theme] .dtt-he__overlay { background: var(--dsw-static-neutral-bluish-1000, #16181d); }',
  '@keyframes dtt-he-zoom { from { opacity: 0; transform: scale(.985) } to { opacity: 1; transform: none } }',
  '.dtt-he__overlay-bar {',
  '  display: flex; align-items: center; gap: 8px; flex: none;',
  '  padding: 10px 12px 10px 16px;',
  '  border-bottom: 1px solid var(--dsw-alias-border-l2, rgba(127,127,127,.16));',
  '}',
  '.dtt-he__overlay-stage { flex: 1; min-height: 0; padding: 12px; }',
  '.dtt-he__overlay-stage .dtt-he__frame { border-radius: 10px; }',
  '/* 无障碍：关掉全部动效 */',
  '@media (prefers-reduced-motion: reduce) {',
  '  .dtt-he, .dtt-he__overlay, .dtt-he__code { animation: none; }',
  '  .dtt-he__stage--settled { transition: none; }',
  '  .dtt-he__btn { transition: none; }',
  '  .dtt-he__btn:hover { transform: none; }',
  '  /* 等待态不能动到 0 反馈：脉冲改成常亮，扫光条停在中间偏左的静止位置，',
  '     否则关掉动效后整张占位卡看起来像卡死了。 */',
  '  .dtt-he__pending-dot { animation: none; opacity: .75; transform: none; }',
  '  .dtt-he__pending-bar { animation: none; transform: translateX(80%); opacity: .6; }',
  '}',
].join('\n')

export function injectHtmlEmbedStyles(): void {
  if (typeof document === 'undefined') return
  if (document.getElementById('dsh-chat-flow-html-embed-styles') !== null) return
  const style = document.createElement('style')
  style.id = 'dsh-chat-flow-html-embed-styles'
  style.textContent = CSS
  document.head.appendChild(style)
}
